# roles/node-cloud/apply.sh — bring up the kiwi-cloud stack.
# shellcheck shell=bash
# shellcheck disable=SC2154
ks_role_apply() {
    local hn=$KS_HOSTNAME
    local dd=$KS_ROLE_DOCKER_DIR
    local dd2=${KS_ROLE_DATA_DIR:-$dd/data}
    local svc_user=$KS_ROLE_SERVICE_USER
    local nc=${KS_ROLE_NC_HOSTNAME:-cloud.$hn}
    local nc_admin=${KS_ROLE_NC_ADMIN_HOSTNAME:-nc-admin.$hn}
    local vault=${KS_ROLE_VAULT_DOMAIN:-https://vault.$hn}
    local nc_data=${KS_ROLE_NEXTCLOUD_DATADIR:-$dd2/knnc-data}
    local compose="docker-compose-kiwi-node-cloud.yml"

    if [[ $dd != /home/user/docker ]]; then
        ks_warn "docker_dir is $dd but kiwi-node.sh hard-codes /home/user/docker — patching the script"
    fi

    ks_ensure_user "$svc_user" 1000
    ks_ensure_docker "${KS_ROLE_DOCKER_SOURCE:-ce}"
    ks_add_to_group "$svc_user" docker
    ks_add_to_group "$KS_ADMIN_USER" docker

    ks_say "fetching $KS_ROLE_REPO ($KS_ROLE_REF) into $dd"
    ks_git_clone "$KS_ROLE_REPO" "$KS_ROLE_REF" "$dd"
    [[ -f $dd/$compose ]] || ks_die "$KS_ROLE_REPO does not contain $compose"
    if [[ $dd != /home/user/docker ]]; then
        sed -i "s|/home/user/docker|$dd|g" "$dd/kiwi-node.sh"
    fi
    install -d -m 0755 "$dd2" "$nc_data" "$dd/knvpn-client" "$dd/knnginx" "$dd/knvault"

    # ---- .env — every key kiwi-cloud's own .env has, from the fleet file -------
    local pub_iface dri=false
    pub_iface=$(ip -o route show default 2>/dev/null | awk '{print $5; exit}')
    [[ -e /dev/dri ]] && dri=true
    local -a env_lines=(
        "### .env for kiwi-node-cloud — generated by kiwi-server $KS_VERSION"
        "## general"
        "TZ=\"$KS_TIMEZONE\""
        "DOCKERDIR=\"$dd\""
        "DOCKERDIR2=\"$dd2\""
        "PUID=$(id -u "$svc_user")"
        "PGID=$(id -g "$svc_user")"
        "HOSTNAME=$hn"
        "NC_HOSTNAME=$nc"
        "NC_ADMIN_HOSTNAME=$nc_admin"
        "PUB_IFACE=${pub_iface:-eth0}"
        "DOCKER_SUBNET=$KS_ROLE_DOCKER_SUBNET"
        "DOCKER_SUBNET2=${KS_ROLE_DOCKER_SUBNET%/*}"
        "VPN_IP=$KS_ROLE_VPN_IP"
        ""
        "# knvpn-client"
        "VPN_PROVIDER=\"custom\""
        "VPN_TYPE=\"$KS_ROLE_VPN_TYPE\""
        "WG_CONFIG=\"$hn.conf\""
        "FIREWALL_INPUT_PORTS=\"\""
        "DOT_PROVIDERS=\"$KS_ROLE_DOT_PROVIDERS\""
        "WIREGUARD_MTU=\"$KS_ROLE_VPN_MTU\""
        ""
        "# knvault"
        "DOMAINVAULT=\"$vault\""
        ""
        "# knnc-aio"
        "AIO_DISABLE_BACKUP_SECTION=false"
        "APACHE_PORT=11000"
        "APACHE_IP_BINDING=127.0.0.1"
        "BORG_RETENTION_POLICY=\"--keep-within=7d --keep-weekly=4 --keep-monthly=6\""
        "COLLABORA_SECCOMP_DISABLED=false"
        "NEXTCLOUD_DATADIR=$nc_data"
        "NEXTCLOUD_UPLOAD_LIMIT=$KS_ROLE_NEXTCLOUD_UPLOAD_LIMIT"
        "NEXTCLOUD_MAX_TIME=360000"
        "NEXTCLOUD_MEMORY_LIMIT=$KS_ROLE_NEXTCLOUD_MEMORY_LIMIT"
        "NEXTCLOUD_STARTUP_APPS=\"$KS_ROLE_NEXTCLOUD_STARTUP_APPS\""
        "NEXTCLOUD_ADDITIONAL_APKS=imagemagick"
        "NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick"
        "NEXTCLOUD_ENABLE_DRI_DEVICE=$dri"
        "NEXTCLOUD_KEEP_DISABLED_APPS=false"
        "TALK_PORT=3478"
        "WATCHTOWER_DOCKER_SOCKET_PATH=/var/run/docker.sock"
    )
    if [[ ${#KS_ROLE_ENV[@]} -gt 0 ]]; then
        env_lines+=("" "# extra entries from fleet.yaml")
        local k
        for k in "${!KS_ROLE_ENV[@]}"; do env_lines+=("$k=${KS_ROLE_ENV[$k]}"); done
    fi
    printf '%s\n' "${env_lines[@]}" | ks_write "$dd/.env" 0600 "$svc_user:$svc_user"

    # ---- secrets and rendered configs -------------------------------------------
    ks_file vpn_config "$dd/knvpn-client/$hn.conf" 0600 "$svc_user:$svc_user"
    if ks_has_file tls_fullchain && ks_has_file tls_privkey; then
        ks_file tls_fullchain "$dd/knnginx/fullchain.pem" 0644
        ks_file tls_privkey   "$dd/knnginx/privkey.pem"   0600
    elif [[ ! -f $dd/knnginx/fullchain.pem ]]; then
        ks_self_signed_cert "$dd/knnginx/fullchain.pem" "$dd/knnginx/privkey.pem" "$hn"
    fi
    # kiwi-node.sh would envsubst these itself, but only if they are missing,
    # and envsubst (gettext) is not on every image — render them here instead.
    # shellcheck disable=SC2034
    local HOSTNAME=$hn NC_HOSTNAME=$nc NC_ADMIN_HOSTNAME=$nc_admin
    # shellcheck disable=SC2034
    local DOCKER_SUBNET=$KS_ROLE_DOCKER_SUBNET DOCKER_SUBNET2=${KS_ROLE_DOCKER_SUBNET%/*} VPN_IP=$KS_ROLE_VPN_IP
    ks_subst "$dd/knnginx/nginx.conf.example" "$dd/knnginx/nginx.conf" HOSTNAME NC_HOSTNAME NC_ADMIN_HOSTNAME
    ks_subst "$dd/knvpn-client/post-rules.txt.example" "$dd/knvpn-client/post-rules.txt" DOCKER_SUBNET DOCKER_SUBNET2 VPN_IP
    chown -R "$svc_user:$svc_user" "$dd"

    if (( KS_ROLE_OPEN_FIREWALL )); then
        ks_firewall_open 80/tcp 443/tcp
    fi

    # ---- the stack as a service: kiwi-node.sh start pulls and starts everything --
    ks_unit kiwi-node.service <<UNIT
[Unit]
Description=kiwi-node (cloud mode) — the kiwi-cloud compose stack
Documentation=$KS_ROLE_REPO
After=docker.service network-online.target
Wants=network-online.target
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$dd
ExecStart=/usr/bin/bash $dd/kiwi-node.sh start
ExecStop=/usr/bin/bash $dd/kiwi-node.sh stop
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
UNIT
    ks_say "starting the stack (first start pulls every image — this takes a while)"
    systemctl enable --now kiwi-node.service
    ks_say "kiwi-node is up: https://$nc (Nextcloud), https://$nc_admin (AIO admin), $vault"
    ks_say "manage it with: sudo bash $dd/kiwi-node.sh start|stop|restart|update"
}
