# roles/master/apply.sh — WireGuard entry point: wg-easy + Pi-hole (+ Portainer).
# shellcheck shell=bash
# shellcheck disable=SC2154
ks_role_apply() {
    local dd=$KS_ROLE_DOCKER_DIR
    local net=$KS_ROLE_DOCKER_SUBNET
    local base=${net%.*}            # 172.130.0.0/24 -> 172.130.0
    local pihole_ip=$base.3 wg_ip=$base.2 portainer_ip=$base.250

    ks_ensure_docker "${KS_ROLE_DOCKER_SOURCE:-ce}"
    ks_add_to_group "$KS_ADMIN_USER" docker
    install -d -m 0750 "$dd"

    # Nothing but the WireGuard port is published on the host. Pi-hole answers
    # on port 53 of its own container address, which VPN clients reach through
    # wg-easy — so the host's own resolver is never in the way.
    ks_write "$dd/docker-compose.yml" 0640 <<COMPOSE
# kiwi-master — generated by kiwi-server $KS_VERSION
services:
  kmwg:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: kmwg
    restart: unless-stopped
    environment:
      - INIT_ENABLED=true
      - INIT_USERNAME=\${WG_ADMIN_USER}
      - INIT_PASSWORD=\${WG_ADMIN_PASSWORD}
      - INIT_HOST=\${WG_HOST}
      - INIT_PORT=\${WG_PORT}
      - INIT_DNS=\${PIHOLE_IP}
      - INIT_IPV4_CIDR=\${WG_CIDR}
      - INIT_IPV6_CIDR=fd42:42:42::/64
      - INIT_ALLOWED_IPS=\${WG_ALLOWED_IPS}
      - DISABLE_IPV6=true
    volumes:
      - kmwg_data:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "\${WG_PORT}:\${WG_PORT}/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      kmnet:
        ipv4_address: $wg_ip
    logging: { driver: json-file, options: { max-size: 10m } }

  kmpihole:
    image: pihole/pihole:latest
    container_name: kmpihole
    restart: unless-stopped
    environment:
      TZ: \${TZ}
      FTLCONF_webserver_api_password: \${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: all
      FTLCONF_dns_upstreams: \${PIHOLE_UPSTREAMS}
    volumes:
      - kmpihole_etc:/etc/pihole
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    networks:
      kmnet:
        ipv4_address: $pihole_ip
    logging: { driver: json-file, options: { max-size: 10m } }
COMPOSE
    if (( KS_ROLE_PORTAINER )); then
        cat >> "$dd/docker-compose.yml" <<COMPOSE

  kmportainer:
    image: portainer/portainer-ce:latest
    container_name: kmportainer
    restart: unless-stopped
    volumes:
      - kmportainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      kmnet:
        ipv4_address: $portainer_ip
    logging: { driver: json-file, options: { max-size: 10m } }
COMPOSE
    fi
    cat >> "$dd/docker-compose.yml" <<COMPOSE

volumes:
  kmwg_data:
  kmpihole_etc:
  kmportainer_data:

networks:
  kmnet:
    name: kmnet
    driver: bridge
    ipam:
      config:
        - subnet: $net
COMPOSE

    {
        echo "# kiwi-master .env — generated by kiwi-server $KS_VERSION"
        echo "TZ=$KS_TIMEZONE"
        echo "WG_HOST=$KS_ROLE_WG_HOST"
        echo "WG_PORT=$KS_ROLE_WG_PORT"
        echo "WG_CIDR=$KS_ROLE_WG_CIDR"
        echo "WG_ALLOWED_IPS=$KS_ROLE_WG_ALLOWED_IPS"
        echo "WG_ADMIN_USER=$KS_ROLE_WG_ADMIN_USER"
        echo "WG_ADMIN_PASSWORD=$KS_ROLE_WG_ADMIN_PASSWORD"
        echo "PIHOLE_IP=$pihole_ip"
        echo "PIHOLE_PASSWORD=$KS_ROLE_PIHOLE_PASSWORD"
        echo "PIHOLE_UPSTREAMS=$KS_ROLE_PIHOLE_UPSTREAMS"
        if [[ ${#KS_ROLE_ENV[@]} -gt 0 ]]; then
            local k
            for k in "${!KS_ROLE_ENV[@]}"; do echo "$k=${KS_ROLE_ENV[$k]}"; done
        fi
    } | ks_write "$dd/.env" 0600

    ks_firewall_open "$KS_ROLE_WG_PORT/udp"

    ks_unit kiwi-master.service <<UNIT
[Unit]
Description=kiwi-master — WireGuard entry point (wg-easy, Pi-hole)
After=docker.service network-online.target
Wants=network-online.target
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$dd
ExecStart=/usr/bin/docker compose up -d --pull always --remove-orphans
ExecStop=/usr/bin/docker compose down
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
UNIT
    ks_say "starting wg-easy and Pi-hole"
    systemctl enable --now kiwi-master.service
    local wg_first=${KS_ROLE_WG_CIDR%.*}.1
    ks_say "kiwi-master is up. Through the tunnel: wg-easy http://$wg_first:51821, Pi-hole http://$pihole_ip/admin"
    if (( KS_ROLE_PORTAINER )); then
        ks_say "Portainer: https://$portainer_ip:9443 (through the tunnel)"
    fi
    ks_say "public: only udp/$KS_ROLE_WG_PORT on $KS_ROLE_WG_HOST"
}
